export const endpoints = {
  auth: {
    signup: "/user/signup",
    login: "/user/login",
    forgotPassword: "/user/forgot-password",
    sendOtp: "/user/send-otp",
    verifyOtp: "/user/verify-otp",
    verifyOtpForgetPassword: "/user/verify-otp-password",
    resendOtp: "/user/resend-verification-token",
    resetPassword: "/user/reset-password",
    changePassword: "/user/change-password",
    logout: "/user/logout",
    editProfile: "/user/edit-profile",
    getProfile: "/user/get-profile",
    checkEmail: "/user/check-email",
    checkUsername: "/user/check-username",
  },
  profile: {
    getFollowings: "/user/get-followings",
    getFollowers: "/user/get-followers",
    getFriends: "/user/friends-data",
    getBadges: "/user/get-user-badges",
    getGroups: "/user/get-user-groups",
    getCities: "/user/get-user-cities",
    getProfileInterests: "/user/get-profile-interest",
    getCityBadges: "/user/get-user-badges-by-city-id",
    createGroup: "/user/add-user-group",
    editGroup: "/user/edit-user-group/",
    followUser: "/user/follow-user",
    unfollowUser: "/user/unfollow-user",
    followReuest: "/user/follow-request",
    cancelFollowRequest: "/user/cancel/follow-request",
    acceptFollowRequest: "/user/accept/follow-request",
    otherUserProfile: "/user/profile",
    searchUser: "/user/search",
    getReferralCode: "/user/referal-code",
    becomeAmbassador: "/user/become-ambassader",
    getBusinessesList: "/user/business/list",
    getTrendingBusinesses: "/user/business/trending",
    getEventsList: "/user/events",
    joinEvent: "/user/join/event",
    getRequestsList: "/user/request/listing",
    getChallenges: "/user/challenges",
    getOffers: "/user/offers",
    businessVisit: "/user/business/visit",
    post: "/user/badge/post",
    editPost: "/user/badge/edit-post/",
    deletePostImage: "/user/badge/delete-post-image/",
    offerNamesListing: "/user/all-offers/",
    badgeVisibility: "/user/badge/visibility",
    holdBadge: "/user/badge/hold",
    pendingPosts: "/user/pending/badges",
    friends: "/user/filter/friend",
    businessProfile: "/user/business/",
    badge: "/user/badge/",
    makePostPublicPrivate: "/user/badge-post/visibility/",
    deleteBadgePost: "/user/badge-post/delete/",
    deleteBadge: "/user/badge/delete/",
    home: "/user/feeds",
    stories: "/user/feed/stories",
    deleteStory: "/user/delete_story",
    boost: "/user/boost/feed",
    profileInterests: "/user/profile/interest",
    otherUserProfileInterests: "/user/profile/",
    postStory: "/user/story",
    businessTypes: "/user/business/types",
    stickers: "/user/business/types",
    getGiftItems: "/user/rewards",
    availReward: "/user/collect/reward",
    collectedReward: "/user/collected/reward",
    notifiations: "/user/notifications",
    publicePrivate: "/user/profile/visibility",
    saveBusiness: "/user/save/business",
    deleteAccount: "/user/delete",
    deleteBadgeGroup: "/user/delete-user-group",
    unlockFact: "/user/get-user-didyouknow-unlock",
  },
  eventsChallengesOffers: {
    events: "/user/get-events/",
    challenges: "/user/get-challenges",
    offers: "/user/get-offers",
  },
  general: {
    getCountries: "/user/get-countries",
  },
  chat: {
    send: "/user/send-message",
  },
};

export const base_url =
  "https://custom-dev.onlinetestingserver.com/tickd/api/v1";
export const web_url = "https://dev124.onlinetestingserver.com/";
// export const base_url = 'https://custom-dev.onlinetestingserver.com/tickd-new/api/v1';
// export const web_url = 'https://custom-dev.onlinetestingserver.com/tickd-new/';
